### PR TITLE
fix(daf-did-jwt): Fix parsing of JWT with missing `typ` in header

### LINKED ISSUE #291: daf7 with schemaValidation on can't use universal resolver
**Bug severity**
3

**Describe the bug**
When using `DafResolverUniversal`, the DID documents are formatted closer to did core spec (they have @context as array of strings)
This causes failures with INVALID_TYPE errors when resolving DIDs

**To Reproduce**
```typescript
import { DafUniversalResolver } from 'daf-resolver-universal'
import { createAgent, IResolver } from 'daf-core'
;(async ()=>{
  const agent = createAgent<IResolver>({
    schemaValidation: true,
    plugins: [
      new DafUniversalResolver({ url: 'https://dev.uniresolver.io/1.0/identifiers/'}),
      //...
    ],
  })
    const doc = await agent.resolveDid({ didUrl: 'did:key:z6Mkfriq1MqLBoPWecGoDLjguo1sB9brj6wT3qZ5BxkKpuP6' })
})();
```

**Expected behaviour**
A `doc` is returned

**Observed behaviour**
`INVALID_TYPE` error is thrown

**Additional context**
The data types in question are imported from `did-resolver`, sometimes indirectly through `did-jwt`.
The latest versions of both these libraries have fixed these definitions.

**Versions (please complete the following information):**
 - Daf: 7.0.0-beta.55

### PR DESCRIPTION
**Pull request by mirceanis**
`JwtMessageHandler` can parse them but they fail later in the the message handler chain if `typ` is missing.

Also, this fixes #291

### CODE REVIEW

File: packages/daf-did-jwt/src/message-handler.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export class JwtMessageHandler extends AbstractMessageHandler {
         const resolver = { resolve: (didUrl: string) => context.agent.resolveDid({ didUrl }) }
         const verified = await verifyJWT(message.raw, { resolver, audience })
         debug('Message.raw is a valid JWT')
-        message.addMetaData({ type: decoded.header.typ, value: decoded.header.alg })
+        message.addMetaData({ type: decoded.header.typ || 'JWT', value: decoded.header.alg })
```
Comment (simonas-notcat) [inline packages/daf-did-jwt/src/message-handler.ts:22]: Do we need to make any changes here? https://github.com/uport-project/daf/blob/beta/packages/daf-w3c/src/message-handler.ts#L51

**Review by simonas-notcat — COMMENTED** [review]
Looks good. But not sure about `daf-w3c` message handler

File: packages/daf-did-jwt/src/message-handler.ts (hunk 1 above)
Comment (mirceanis) [reply packages/daf-did-jwt/src/message-handler.ts:22]: @simonas-notcat Yes, definitely, but it's not in the scope of this PR

daf-w3c benefits from this PR, though
